version: "3.6"
services:
  discovery:
    build: ./EurekaServer
    ports:
      - "3004:8755"
    image: "eureka-service"

  projet:
    build: ./WebDistribu-es-Cyrine
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8755/eureka/
    ports:
      - "3005:9092"
    image: "projet-service"
    depends_on:
      - discovery

  gateway:
    build: ./API-Gateway_Server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8755/eureka/
    ports:
      - "3006:8090"
    image: "gateway-service"
    depends_on:
      - discovery

